name: Terraform Workflow

on: workflow_dispatch

jobs:
  my_first_job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        
      - name: Greetings
        run: echo " my first pepiline demo"
